plugins {
    kotlin("multiplatform") version "2.2.0"
    id("org.jetbrains.compose") version "1.7.3"
    id("org.jetbrains.kotlin.plugin.compose") version "2.2.0"
}

group = "com.skaldoria"

/**
 * Single source of truth for the app version.
 *
 * Feeds the Gradle project version, the native installer version, and the generated
 * `BuildInfo.VERSION` the UI displays — previously the number was written out twice here
 * and was not reachable from Kotlin at all, so the running app could not report itself.
 */
val appVersion = "1.2.0"
version = appVersion

/** Single version for every coroutines artifact, so `-core` and `-swing` cannot drift. */
val coroutinesVersion = "1.11.0"

/**
 * Emits `BuildInfo.kt` so the version is available at runtime.
 *
 * Declared with proper inputs/outputs so Gradle can skip it when unchanged; the file is
 * generated rather than committed to keep one authority for the number.
 */
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val outputDir = layout.buildDirectory.dir("generated/source/buildinfo")
    inputs.property("appVersion", appVersion)
    outputs.dir(outputDir)

    doLast {
        val packageDir = outputDir.get().asFile.resolve("com/skaldoria")
        packageDir.mkdirs()
        packageDir.resolve("BuildInfo.kt").writeText(
            """
            package com.skaldoria

            /**
             * Build metadata generated by the `generateBuildInfo` Gradle task.
             * Do not edit — change `appVersion` in build.gradle.kts instead.
             */
            object BuildInfo {
                const val VERSION: String = "$appVersion"

                /** Version prefixed for display, e.g. `v1.0.0`. */
                const val DISPLAY_VERSION: String = "v$appVersion"
            }

            """.trimIndent()
        )
    }
}

kotlin {
    jvm("desktop")

    sourceSets {
        val desktopMain = getByName("desktopMain") {
            // Passing the task provider (not a path) lets Gradle wire the dependency itself.
            kotlin.srcDir(generateBuildInfo)

            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)

                // JetBrains Official Markdown AST parser
                implementation("org.jetbrains:markdown:0.7.8")

                // Coroutines & Desktop Swing dispatcher.
                //
                // Both must move together. `-swing` was pinned at 1.1.0 (2018) against a
                // 1.11.0 core: harmless in practice, because the coroutines BOM lifted it,
                // but it read as a live version and hid that the two had drifted.
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:$coroutinesVersion")
            }
        }
        val desktopTest = getByName("desktopTest") {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

/**
 * COR-11: redirects `ConfigManager` at its `skaldoria.configDir` injection point so the test
 * suite persists under `build/` instead of the developer's real `~/.skaldoria`.
 *
 * `PresentationState` autosaves through `ConfigManager`, and that class is constructed in 20+
 * test cases, so before this the suite wrote a real draft and config on every run. Setting it
 * on the task makes every test hermetic without each one having to remember to redirect.
 */
tasks.withType<Test>().configureEach {
    systemProperty(
        "skaldoria.configDir",
        layout.buildDirectory.dir("test-config").get().asFile.absolutePath
    )
}

compose.desktop {
    application {
        mainClass = "com.skaldoria.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Exe,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Rpm,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Pkg
            )
            packageName = "Skaldoria"
            packageVersion = appVersion
            description = "Skaldoria — Native Markdown Presentation Studio"
            vendor = "Skaldoria"

            val iconsDir = project.file("src/desktopMain/resources/icons")
            windows {
                iconFile.set(iconsDir.resolve("app.ico"))
            }
            linux {
                iconFile.set(iconsDir.resolve("app.png"))
            }
        }
    }
}
