plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose)
    alias(libs.plugins.kotlin.compose)
    // Declared here so `:skaldoria-markdown` can apply it without restating the version.
    alias(libs.plugins.kotlin.jvm) apply false
}

group = "com.skaldoria"

/**
 * Single source of truth for the app version.
 *
 * Feeds the Gradle project version, the native installer version, and the generated
 * `BuildInfo.VERSION` the UI displays — previously the number was written out twice here
 * and was not reachable from Kotlin at all, so the running app could not report itself.
 */
val appVersion = "1.2.0"
version = appVersion

/**
 * Emits `BuildInfo.kt` so the version is available at runtime.
 *
 * Declared with proper inputs/outputs so Gradle can skip it when unchanged; the file is
 * generated rather than committed to keep one authority for the number.
 */
val generateBuildInfo = tasks.register("generateBuildInfo") {
    group = "build"
    description = "Generates the BuildInfo Kotlin source with build metadata (e.g. app version)."
    val outputDir = layout.buildDirectory.dir("generated/source/buildinfo")
    inputs.property("appVersion", appVersion)
    outputs.dir(outputDir)

    doLast {
        val packageDir = outputDir.get().asFile.resolve("com/skaldoria")
        packageDir.mkdirs()
        packageDir.resolve("BuildInfo.kt").writeText(
            """
            package com.skaldoria

            /**
             * Build metadata generated by the `generateBuildInfo` Gradle task.
             * Do not edit — change `appVersion` in build.gradle.kts instead.
             */
            object BuildInfo {
                const val VERSION: String = "$appVersion"

                /** Version prefixed for display, e.g. `v1.0.0`. */
                const val DISPLAY_VERSION: String = "v$appVersion"
            }

            """.trimIndent()
        )
    }
}

/**
 * Makes `appVersion` readable from outside Gradle.
 *
 * The release scripts used to carry their own `1.0.0` default, so running one without an
 * explicit argument produced `Skaldoria-v1.0.0-*` artefacts from a 1.2.0 build. They now ask
 * this task instead, which keeps the "single source of truth" above honest rather than merely
 * claimed.
 *
 *     ./gradlew -q printVersion
 */
tasks.register("printVersion") {
    group = "help"
    description = "Prints the application version, for the local release scripts to read."
    // Captured at configuration time so the task body touches no project state.
    val versionToPrint = appVersion
    doLast { println(versionToPrint) }
}

kotlin {
    jvm("desktop")

    /**
     * The zero-warning NFR, enforceable.
     *
     * Off by default so a local build stays workable mid-edit, and turned on with
     * `-PwarningsAsErrors` by `scripts/verify.ps1` and by both release pipelines. CI is
     * deferred on cost (`PLT-01`), so the gate lives where the release is actually cut; the
     * flag is kept property-driven precisely so a workflow can set it unchanged if one ever
     * arrives. Without a gate the NFR is a wish: the Kotlin compiler does not
     * report unused *public* declarations at all, so several dead functions sat in this
     * codebase through a full release with a green build.
     */
    compilerOptions {
        allWarningsAsErrors.set(providers.gradleProperty("warningsAsErrors").isPresent)
    }

    sourceSets {
        getByName("desktopMain") {
            // Passing the task provider (not a path) lets Gradle wire the dependency itself.
            kotlin.srcDir(generateBuildInfo)

            dependencies {
                // The Markdown engine, Compose-free by construction. See skaldoria-markdown/build.gradle.kts.
                implementation(project(":skaldoria-markdown"))

                implementation(compose.desktop.currentOs)
                implementation(libs.compose.material3)
                implementation(libs.compose.material.icons.extended)
                implementation(libs.compose.components.resources)

                // Coroutines & Desktop Swing dispatcher.
                //
                // Both must move together. `-swing` was pinned at 1.1.0 (2018) against a
                // 1.11.0 core: harmless in practice, because the coroutines BOM lifted it,
                // but it read as a live version and hid that the two had drifted.
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.coroutines.swing)
            }
        }
        getByName("desktopTest") {
            dependencies {
                // kotlin.test backed by JUnit 5 (Jupiter); junit-jupiter pulls the engine so the
                // JUnit Platform can run these tests. JUnit 4 is deliberately not on the classpath.
                implementation(kotlin("test-junit5"))
                implementation(libs.junit.jupiter)
            }
        }
    }
}

/**
 * COR-11: redirects `ConfigManager` at its `skaldoria.configDir` injection point so the test
 * suite persists under `build/` instead of the developer's real `~/.skaldoria`.
 *
 * `PresentationState` autosaves through `ConfigManager`, and that class is constructed in 20+
 * test cases, so before this the suite wrote a real draft and config on every run. Setting it
 * on the task makes every test hermetic without each one having to remember to redirect.
 */
tasks.withType<Test>().configureEach {
    // JUnit 5 only — kotlin.test is wired to Jupiter via kotlin("test-junit5").
    useJUnitPlatform()

    systemProperty(
        "skaldoria.configDir",
        layout.buildDirectory.dir("test-config").get().asFile.absolutePath
    )

    /**
     * PLT-08: lets the render guards be stood down from the command line.
     *
     * Tests run in a forked JVM, so a `-D` on the Gradle invocation does not reach them — it
     * configures the daemon and the guards keep rendering, which is exactly the false negative
     * this forwarding removes. `RenderEnvironment` also detects a genuinely headless machine on
     * its own; this is the explicit override for the case where a display exists but rendering
     * still should not be attempted.
     *
     *     ./gradlew desktopTest -PskipRenderTests
     */
    if (providers.gradleProperty("skipRenderTests").isPresent) {
        systemProperty("skaldoria.skipRenderTests", "true")
    }
}

compose.desktop {
    application {
        mainClass = "com.skaldoria.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Exe,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Rpm,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Pkg
            )
            packageName = "Skaldoria"
            packageVersion = appVersion
            description = "Skaldoria - Native Markdown Presentation Studio"
            vendor = "Skaldoria"

            val iconsDir = project.file("src/desktopMain/resources/icons")
            windows {
                iconFile.set(iconsDir.resolve("app.ico"))
            }
            linux {
                iconFile.set(iconsDir.resolve("app.png"))
            }
        }
    }
}
