plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose)
    alias(libs.plugins.kotlin.compose)
}

group = "com.skaldoria.canvas"
version = rootProject.version

/**
 * Emits `com.skaldoria.canvas.BuildInfo` so the running Canvas app can report its own version.
 *
 * Mirrors the root module's `generateBuildInfo`: the number stays a single source of truth
 * (`rootProject.version`, i.e. `appVersion` in the root build) rather than being restated here.
 * Declared with inputs/outputs so Gradle skips it when unchanged.
 */
val canvasVersion = rootProject.version.toString()
val generateCanvasBuildInfo = tasks.register("generateCanvasBuildInfo") {
    group = "build"
    description = "Generates the Canvas BuildInfo Kotlin source with the app version."
    val outputDir = layout.buildDirectory.dir("generated/source/buildinfo")
    inputs.property("canvasVersion", canvasVersion)
    outputs.dir(outputDir)

    doLast {
        val packageDir = outputDir.get().asFile.resolve("com/skaldoria/canvas")
        packageDir.mkdirs()
        packageDir.resolve("BuildInfo.kt").writeText(
            """
            package com.skaldoria.canvas

            /**
             * Build metadata generated by the `generateCanvasBuildInfo` Gradle task.
             * Do not edit — change `appVersion` in the root build.gradle.kts instead.
             */
            object BuildInfo {
                const val VERSION: String = "$canvasVersion"

                /** Version prefixed for display, e.g. `v1.0.0`. */
                const val DISPLAY_VERSION: String = "v$canvasVersion"
            }

            """.trimIndent()
        )
    }
}

kotlin {
    jvm("desktop")

    compilerOptions {
        allWarningsAsErrors.set(providers.gradleProperty("warningsAsErrors").isPresent)
    }

    sourceSets {
        getByName("desktopMain") {
            // Passing the task provider (not a path) lets Gradle wire the dependency itself.
            kotlin.srcDir(generateCanvasBuildInfo)

            dependencies {
                implementation(project(":skaldoria-markdown"))
                implementation(project(":skaldoria-shared-ui"))
                
                implementation(compose.desktop.currentOs)
                implementation(libs.compose.material3)
                implementation(libs.compose.material.icons.extended)
                implementation(libs.compose.components.resources)

                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.coroutines.swing)
            }
        }

        getByName("desktopTest") {
            dependencies {
                implementation(kotlin("test"))
                @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
                implementation(compose.uiTest)
                implementation(compose.desktop.currentOs)
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.skaldoria.canvas.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Exe,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Rpm,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Pkg
            )
            packageName = "SkaldoriaCanvas"
            packageVersion = rootProject.version.toString()
            description = "Skaldoria Canvas - Spatial Markdown Whiteboard & Presentation Compiler"
            vendor = "Skaldoria"

            val iconsDir = project.file("src/desktopMain/resources/icons")
            windows {
                iconFile.set(iconsDir.resolve("canvas.ico"))
            }
            linux {
                iconFile.set(iconsDir.resolve("canvas.png"))
            }
        }
    }
}
